- id: obsolete-messages
  name: obsolete-messages
  entry: obsolete-messages-hook
  description: Checks for obsolete messages in PO files
  files: \.po$
  language: python
- id: untranslated-messages
  name: untranslated-messages
  entry: untranslated-messages-hook
  description: Checks for untranslated messages in PO files
  files: \.po$
  language: python
- id: remove-django-translators
  name: remove-django-translators
  entry: lreplace-extracted-comments-hook --django-translators
  description: Removes the "Translator" string prepended by Django extracting messages con xgettext
  files: \.po$
  language: python
- id: lreplace-extracted-comments
  name: lreplace-extracted-comments
  entry: lreplace-extracted-comments-hook
  description: Replaces a string matching at the beginning of extracted comments
  files: \.po$
  language: python
- id: check-metadata
  name: check-metadata
  entry: check-metadata-hook
  description: Checks that the metadata values of your PO files matchs against some regexes
  files: \.po$
  language: python
- id: standard-metadata
  name: standard-metadata
  entry: check-metadata-hook --standard-headers
  description: Checks that the metadata of your PO files fits a set of standard requirements
  files: \.po$
  language: python
- id: no-metadata
  name: no-metadata
  entry: check-metadata-hook --no-metadata
  description: Checks that your PO files don't contain metadata headers
  files: \.po$
  language: python
- id: remove-metadata
  name: remove-metadata
  entry: check-metadata-hook --no-metadata --remove-metadata
  description: Removes metadata headers from your PO files
  files: \.po$
  language: python
- id: check-entries
  name: check-entries
  entry: check-entries-hook
  description: Check that PO files entries match a set of requirements passed by parameters
  files: \.po$
  language: python
- id: max-messages
  name: max-messages
  entry: check-entries-hook --max-messages
  description: Checks that each one of your PO files don't contain more than X messages
  files: \.po$
  language: python
- id: max-lines
  name: max-lines
  entry: check-entries-hook --max-lines
  description: Checks that each one of your PO files don't contain more than X lines
  files: \.po$
  language: python
- id: min-translated
  name: min-translated
  entry: untranslated-messages-hook --min
  description: Checks that each one of your PO files has at least a number or a parcentage of messages translated
  files: \.po$
  language: python
