- id: obsolete-messages
  name: obsolete-messages
  entry: obsolete-messages-hook
  description: Checks for obsolete messages in PO files
  files: \.po$
  language: python
- id: untranslated-messages
  name: untranslated-messages
  entry: untranslated-messages-hook
  description: Checks for untranslated messages in PO files
  files: \.po$
  language: python
- id: lreplace-extracted-comments
  name: lreplace-extracted-comments
  entry: lreplace-extracted-comments-hook
  description: Replaces a string matching at the beginning of extracted comments
  files: \.po$
  language: python
- id: check-metadata
  name: check-metadata
  entry: check-metadata-hook
  description: Checks that the metadata values of your PO files matchs against some regexes
  files: \.po$
  language: python
